/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTransfersRouteImport } from './routes/_app.transfers'
import { Route as AppTrackingRouteImport } from './routes/_app.tracking'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppRoiRouteImport } from './routes/_app.roi'
import { Route as AppQueueRouteImport } from './routes/_app.queue'
import { Route as AppMyCasesRouteImport } from './routes/_app.my-cases'
import { Route as AppModerationRouteImport } from './routes/_app.moderation'
import { Route as AppMibRouteImport } from './routes/_app.mib'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppFieldRouteImport } from './routes/_app.field'
import { Route as AppCourtRouteImport } from './routes/_app.court'
import { Route as AppControlTowerRouteImport } from './routes/_app.control-tower'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAssignmentsRouteImport } from './routes/_app.assignments'
import { Route as AppAgenciesRouteImport } from './routes/_app.agencies'
import { Route as AppPortfolioUploadRouteImport } from './routes/_app.portfolio.upload'
import { Route as AppCasesIdRouteImport } from './routes/_app.cases_.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppRoiRoute = AppRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppMyCasesRoute = AppMyCasesRouteImport.update({
  id: '/my-cases',
  path: '/my-cases',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppMibRoute = AppMibRouteImport.update({
  id: '/mib',
  path: '/mib',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldRoute = AppFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AppRoute,
} as any)
const AppCourtRoute = AppCourtRouteImport.update({
  id: '/court',
  path: '/court',
  getParentRoute: () => AppRoute,
} as any)
const AppControlTowerRoute = AppControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenciesRoute = AppAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioUploadRoute = AppPortfolioUploadRouteImport.update({
  id: '/portfolio/upload',
  path: '/portfolio/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIdRoute = AppCasesIdRouteImport.update({
  id: '/cases_/$id',
  path: '/cases/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agencies': typeof AppAgenciesRoute
  '/assignments': typeof AppAssignmentsRoute
  '/audit': typeof AppAuditRoute
  '/cases': typeof AppCasesRoute
  '/control-tower': typeof AppControlTowerRoute
  '/court': typeof AppCourtRoute
  '/field': typeof AppFieldRoute
  '/integrations': typeof AppIntegrationsRoute
  '/mib': typeof AppMibRoute
  '/moderation': typeof AppModerationRoute
  '/my-cases': typeof AppMyCasesRoute
  '/queue': typeof AppQueueRoute
  '/roi': typeof AppRoiRoute
  '/team': typeof AppTeamRoute
  '/tracking': typeof AppTrackingRoute
  '/transfers': typeof AppTransfersRoute
  '/users': typeof AppUsersRoute
  '/cases/$id': typeof AppCasesIdRoute
  '/portfolio/upload': typeof AppPortfolioUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agencies': typeof AppAgenciesRoute
  '/assignments': typeof AppAssignmentsRoute
  '/audit': typeof AppAuditRoute
  '/cases': typeof AppCasesRoute
  '/control-tower': typeof AppControlTowerRoute
  '/court': typeof AppCourtRoute
  '/field': typeof AppFieldRoute
  '/integrations': typeof AppIntegrationsRoute
  '/mib': typeof AppMibRoute
  '/moderation': typeof AppModerationRoute
  '/my-cases': typeof AppMyCasesRoute
  '/queue': typeof AppQueueRoute
  '/roi': typeof AppRoiRoute
  '/team': typeof AppTeamRoute
  '/tracking': typeof AppTrackingRoute
  '/transfers': typeof AppTransfersRoute
  '/users': typeof AppUsersRoute
  '/cases/$id': typeof AppCasesIdRoute
  '/portfolio/upload': typeof AppPortfolioUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/agencies': typeof AppAgenciesRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/control-tower': typeof AppControlTowerRoute
  '/_app/court': typeof AppCourtRoute
  '/_app/field': typeof AppFieldRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/mib': typeof AppMibRoute
  '/_app/moderation': typeof AppModerationRoute
  '/_app/my-cases': typeof AppMyCasesRoute
  '/_app/queue': typeof AppQueueRoute
  '/_app/roi': typeof AppRoiRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/tracking': typeof AppTrackingRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/cases_/$id': typeof AppCasesIdRoute
  '/_app/portfolio/upload': typeof AppPortfolioUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/agencies'
    | '/assignments'
    | '/audit'
    | '/cases'
    | '/control-tower'
    | '/court'
    | '/field'
    | '/integrations'
    | '/mib'
    | '/moderation'
    | '/my-cases'
    | '/queue'
    | '/roi'
    | '/team'
    | '/tracking'
    | '/transfers'
    | '/users'
    | '/cases/$id'
    | '/portfolio/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/agencies'
    | '/assignments'
    | '/audit'
    | '/cases'
    | '/control-tower'
    | '/court'
    | '/field'
    | '/integrations'
    | '/mib'
    | '/moderation'
    | '/my-cases'
    | '/queue'
    | '/roi'
    | '/team'
    | '/tracking'
    | '/transfers'
    | '/users'
    | '/cases/$id'
    | '/portfolio/upload'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_app/agencies'
    | '/_app/assignments'
    | '/_app/audit'
    | '/_app/cases'
    | '/_app/control-tower'
    | '/_app/court'
    | '/_app/field'
    | '/_app/integrations'
    | '/_app/mib'
    | '/_app/moderation'
    | '/_app/my-cases'
    | '/_app/queue'
    | '/_app/roi'
    | '/_app/team'
    | '/_app/tracking'
    | '/_app/transfers'
    | '/_app/users'
    | '/_app/cases_/$id'
    | '/_app/portfolio/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking': {
      id: '/_app/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roi': {
      id: '/_app/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof AppRoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queue': {
      id: '/_app/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-cases': {
      id: '/_app/my-cases'
      path: '/my-cases'
      fullPath: '/my-cases'
      preLoaderRoute: typeof AppMyCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mib': {
      id: '/_app/mib'
      path: '/mib'
      fullPath: '/mib'
      preLoaderRoute: typeof AppMibRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/field': {
      id: '/_app/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AppFieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/court': {
      id: '/_app/court'
      path: '/court'
      fullPath: '/court'
      preLoaderRoute: typeof AppCourtRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control-tower': {
      id: '/_app/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof AppControlTowerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agencies': {
      id: '/_app/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AppAgenciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio/upload': {
      id: '/_app/portfolio/upload'
      path: '/portfolio/upload'
      fullPath: '/portfolio/upload'
      preLoaderRoute: typeof AppPortfolioUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases_/$id': {
      id: '/_app/cases_/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof AppCasesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgenciesRoute: typeof AppAgenciesRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCasesRoute: typeof AppCasesRoute
  AppControlTowerRoute: typeof AppControlTowerRoute
  AppCourtRoute: typeof AppCourtRoute
  AppFieldRoute: typeof AppFieldRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMibRoute: typeof AppMibRoute
  AppModerationRoute: typeof AppModerationRoute
  AppMyCasesRoute: typeof AppMyCasesRoute
  AppQueueRoute: typeof AppQueueRoute
  AppRoiRoute: typeof AppRoiRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppCasesIdRoute: typeof AppCasesIdRoute
  AppPortfolioUploadRoute: typeof AppPortfolioUploadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenciesRoute: AppAgenciesRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCasesRoute: AppCasesRoute,
  AppControlTowerRoute: AppControlTowerRoute,
  AppCourtRoute: AppCourtRoute,
  AppFieldRoute: AppFieldRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMibRoute: AppMibRoute,
  AppModerationRoute: AppModerationRoute,
  AppMyCasesRoute: AppMyCasesRoute,
  AppQueueRoute: AppQueueRoute,
  AppRoiRoute: AppRoiRoute,
  AppTeamRoute: AppTeamRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppUsersRoute: AppUsersRoute,
  AppCasesIdRoute: AppCasesIdRoute,
  AppPortfolioUploadRoute: AppPortfolioUploadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
